// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoolEvents.Models
{
    [Table("Event")]
    public partial class Event
    {
        public Event()
        {
            Tickets = new HashSet<Ticket>();
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(64)]
        public string Name { get; set; }

        [Required]
        [StringLength(255)]
        public string Description { get; set; }

        public byte[] Image { get; set; }

        [NotMapped]
        [Display(Name = "Event Image")]
        public IFormFile ImageFile { get; set; }

        [Column(TypeName = "date")]
        public DateTime Date { get; set; }

        [InverseProperty("Event")]
        public virtual ICollection<Ticket> Tickets { get; set; }

        public bool IsValidImage()
        {
            if (ImageFile == null)
            {
                return false;
            }

            var validTypes = new[] { "image/jpeg", "image/png", "image/gif" };
            if (!validTypes.Contains(ImageFile.ContentType))
            {
                return false;
            }

            return true;
        }
    }
}