// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoolEvents.Models
{
    [Table("Event")]
    public partial class Event
    {
        public Event()
        {
            Tickets = new HashSet<Ticket>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(64)]
        public string Name { get; set; }
        [Required]
        [StringLength(255)]
        public string Description { get; set; }
        [Required]
        public byte[] Image { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }

        [InverseProperty("Event")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}